---
triple:          'arm64-apple-darwin'
binary-path:     stack
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _stack_init, symObjAddr: 0x0, symBinAddr: 0x100003C2C, symSize: 0xA8 }
  - { offsetInCU: 0x4D, offset: 0x4D, size: 0x8, addend: 0x0, symName: _stack_init, symObjAddr: 0x0, symBinAddr: 0x100003C2C, symSize: 0xA8 }
  - { offsetInCU: 0x7F, offset: 0x7F, size: 0x8, addend: 0x0, symName: _stack_push, symObjAddr: 0xA8, symBinAddr: 0x100003CD4, symSize: 0x80 }
  - { offsetInCU: 0xB1, offset: 0xB1, size: 0x8, addend: 0x0, symName: _stack_pop, symObjAddr: 0x128, symBinAddr: 0x100003D54, symSize: 0x6C }
  - { offsetInCU: 0xD5, offset: 0xD5, size: 0x8, addend: 0x0, symName: _print_stack, symObjAddr: 0x194, symBinAddr: 0x100003DC0, symSize: 0x80 }
  - { offsetInCU: 0x10B, offset: 0x10B, size: 0x8, addend: 0x0, symName: _peek_s, symObjAddr: 0x214, symBinAddr: 0x100003E40, symSize: 0x5C }
  - { offsetInCU: 0x133, offset: 0x133, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x270, symBinAddr: 0x100003E9C, symSize: 0x78 }
...
