---
triple:          'arm64-apple-darwin'
binary-path:     stack
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _make_v, symObjAddr: 0x0, symBinAddr: 0x100003DC0, symSize: 0xA8 }
  - { offsetInCU: 0x4D, offset: 0x4D, size: 0x8, addend: 0x0, symName: _make_v, symObjAddr: 0x0, symBinAddr: 0x100003DC0, symSize: 0xA8 }
  - { offsetInCU: 0x7F, offset: 0x7F, size: 0x8, addend: 0x0, symName: _push, symObjAddr: 0xA8, symBinAddr: 0x100003E68, symSize: 0x4 }
  - { offsetInCU: 0x94, offset: 0x94, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0xAC, symBinAddr: 0x100003E6C, symSize: 0xC8 }
...
